version: "3.1"
services:
    db:
        image: postgres:16
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo_db_data:/var/lib/postgresql/data/pgdata
        ports:
            - "5433:5432"

    odoo:
        image: odoo:17
        depends_on:
            - db
        ports:
            - "8069:8069"
        volumes:
            - odoo_data:/var/lib/odoo
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
        environment:
            - HOST=db
            - PORT=5432
            - USER=odoo
            - PASSWORD=odoo
volumes:
    odoo_data:
    odoo_db_data:
